#!/usr/bin/env python2

"""
Etch-a-Sketch

"""

from surgitouch.windows import Visualiser

from shapely.geometry import Point


if __name__ == '__main__':
  vis = Visualiser(size=(1000, 1000))
  vis.etch_a_sketch()
